#!/bin/bash

if [[ $EUID -ne 0 ]]; then
  echo "This script must be run as root" 
  exit 1
fi

if [[ -d /usr/share/Nightmare ]]; then
    cd /usr/share/Nightmare
    python3 Nightmare.py    
else
    echo "/usr/share/Nightmare doesn't exist.\nPlease run the setup script again"
fi